#!/bin/bash -eu
usage() { 
	echo "Usage: $0 [-s]" 1>&2
	exit 1
}

slow=''
local=''
while getopts "ls" optionen; do
    case "${optionen}" in
        l) local='-local_stores' ;;
        s) slow='-r' ;;
        *) usage ;;
    esac
done
delay=200
shift $((OPTIND-1))
thisDir=$(dirname $0)
cd $thisDir
name=${1:-blanton}
./utah_abc_poller.pl $local $slow -y $name > pollingData/$name.current
mkdir -p log/
touch pollingData/$name
cp pollingData/$name pollingData/$name.prior

while true
do
	python -c 'import sys,Quartz; d=Quartz.CGSessionCopyCurrentDictionary(); print d' | grep -qi lock || break
	sleep 10
	delay=5
	echo -n .x
done
diff -q pollingData/$name.prior pollingData/$name.current > /dev/null && while :; do
currenttime=$(date +%H:%M)
	if [[ "$currenttime" > "20:00" ]] || [[ "$currenttime" < "09:30" ]]; then
		sleep 200
		echo -n .z
	else
		exit $delay
	fi
done

diff -y -W 220 pollingData/$name.prior pollingData/$name.current | tee -a log/$name
date >> log/$name


say $name || true

cp pollingData/$name.current pollingData/$name

exit $delay
